import struct

VERSION = 1

FRAME_GET = 1
FRAME_RESPONSE = 2
FRAME_PING = 3

STATUS_OK = 200
STATUS_BAD_REQUEST = 400
STATUS_NOT_FOUND = 404

REQUEST_HEADER_FORMAT = "!BBBBI"

RESPONSE_HEADER_FORMAT = "!BBHII"

REQUEST_HEADER_SIZE = struct.calcsize(
    REQUEST_HEADER_FORMAT
)

RESPONSE_HEADER_SIZE = struct.calcsize(
    RESPONSE_HEADER_FORMAT
)